---
title: "PBMC Flex"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(Seurat)
library(BPCells)
library(tidyverse)
# needs to be set for large dataset analysis
options(future.globals.maxSize = 5e9)

# get a list of all the .h5 files exported from CellRanger
files <- list.files("data/input", recursive = TRUE, 
  full.names = TRUE) %>% 
  # ONLY include the "sample_filtered_feature_bc_matrix.h5" files, 
  # ignore all others
  .[str_detect(., "sample_filtered_feature_bc_matrix.h5")]

# convert file names vector to a dataframe containing the full file names
# as well as the corresponding GEM and Sample name
files_df <- tibble(Files = files) %>% 
  mutate(GEM = str_extract(Files, "GEM.")) %>% 
  mutate(Sample = str_extract(Files, "MP-\\d\\d*"))
```

```{r functions}
# THIS CHUNK INCLUDES FUNCTIONS TO READ IN THE RAW FILES

# read in one h5 file, create a Seurat object, add metadata
# the function takes a single row of a data frame
#     the data frame should include the file name, the GEM, and the Sample
# add GEM and Sample to the meta.data of the resulting Seurat object
read_one_file <- function(files_df_row) {
  one_file <- Read10X_h5(files_df_row$Files) %>% CreateSeuratObject()
  # add metadata
  one_file$GEM <- files_df_row$GEM
  one_file$Sample <- files_df_row$Sample
  
  one_file
}

# use the BPCells package to put a Seurat object on disk to save memory
put_on_disk <- function(obj) {
  sample_id <- obj@meta.data$Sample[1]
  
  write_matrix_dir(mat = obj[["RNA"]]$counts, dir = paste0('data/temp/', sample_id))
  counts.mat <- open_matrix_dir(dir = paste0('data/temp/', sample_id))
  obj[["RNA"]]$counts <- counts.mat
  
  obj  
}

# read and combine all four GEM files for 1 sample
# Each sample is split across the 4 GEMs
# Given a sample name (e.g. "MP-1"), this function reads the 
# 4 h5 files for the sample (from each GEM) and combines them
# Then it puts the object on disk to save memory
read_one_sample <- function(sample) {
  # filter for the files just for one sample
  one_sample <- files_df %>% 
    filter(Sample == sample)
  
  # read in all 4 GEMs for one sample
  one_sample_list <- list(
    read_one_file(one_sample[1,]),
    read_one_file(one_sample[2,]),
    read_one_file(one_sample[3,]),
    read_one_file(one_sample[4,])
  )
  
  # merge together the four samples
  one_sample_merged <- merge(
                        # select first list element
                        one_sample_list[[1]],
                        # merge with every element except the first
                        one_sample_list[-1], 
                        add.cell.ids = c("GEM1", "GEM2", "GEM3", "GEM4") 
                       )

  
  # JoinLayers converts from one "counts layer" per GEM
  # to one per sample
  one_sample_merged %>% 
    JoinLayers() %>% 
    put_on_disk()
}

# test code to make sure each function works
# sample_1 <- read_one_sample("MP-1")
# sample_2 <- read_one_sample("MP-2")
# test <- merge(sample_1, sample_2, add.cell.ids = c("MP-1", "MP-2"))
```

```{r}
# THIS CHUNK READS IN THE RAW FILES AND MERGES THEM INTO A SEURAT OBJECT

# Read in every sample
# This results in a list of seurat objects (one per sample)
all_samples_list <- lapply(unique(files_df$Sample), read_one_sample)

# save list of seurat objects
write_rds(all_samples_list, "data/rds_files/01-list_of_samples.rds")

#read in the saved list of files, not normed yet
# all_samples_list<-read_rds("data/rds_files/01-list_of_samples.rds")

```

```{r}
# THIS CHUNK MERGES THE LIST OF SEURAT OBJECTS INTO A SINGLE OBJECT

# Combine list of seurat objects into a single Seurat object
all_samples_merged <- merge(
                    # select first list element
                    all_samples_list[[1]],
                    # merge with every element except the first
                    all_samples_list[-1], 
  add.cell.ids =  unique(files_df$Sample)
                        )
```

```{r}
# THIS CHUNK CHECKS THE QC METRICS AND FILTERS OUT LOW QUALITY CELLS

# check QC metrics

# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
all_samples_merged[["percent.mt"]] <- PercentageFeatureSet(all_samples_merged, pattern = "^MT-")

# Visualize QC metrics as a violin plot
# have some cells with  really high transcript counts, most cells have info about ~2k genes, a few cells have a higher percentage of mt transcripts

VlnPlot(all_samples_merged, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)

#dropoff at about 20k
all_samples_merged$nCount_RNA  %>%  
    hist(breaks= 100)

#lowest counts are around 450
sort(all_samples_merged$nCount_RNA) %>% tail(n = 20)
#highest are around 140k
sort(all_samples_merged$nCount_RNA) %>% head(n = 20)

all_samples_merged$nFeature_RNA  %>%  
    hist(breaks= 100)

#highest is around 8500
sort(all_samples_merged$nFeature_RNA) %>% tail(n = 20)
#lowest are around 40
sort(all_samples_merged$nFeature_RNA) %>% head(n = 20)


# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.
plot1 <- FeatureScatter(subset(all_samples_merged,downsample = 300), feature1 = "nCount_RNA", feature2 = "percent.mt")


plot2 <- FeatureScatter(subset(all_samples_merged,downsample = 300), feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2



#subset for nCount, nFeature and percent.mt. Tutorial does not have an nCount subset but we are adding one because we don't want info from the cells that only have a few transcripts read
#our cutoffs are based on the histograms made above

all_samples_merged_subset <- subset(all_samples_merged, 
    subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 10 & nCount_RNA < 2E4)

# save merged seurat object
write_rds(all_samples_merged_subset, "data/rds_files/02-merged-subset.rds")

#check violins again after subsetting
VlnPlot(all_samples_merged_subset, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)

#comparing our original and subset objects, we've removed about 5k cells, not much!! Lol
all_samples_merged_subset
all_samples_merged
```



```{r}
# THIS CHUNK RUNS SCTRANSFORM

#instead of normalizeData we're trying the cooler sctransform which is better because...it accounts for sequencing depth?
# we are not regressing out any of our variables, we aren't sure if they are important. We ran out of memory on Sean's 16gb machine doing this.
#Running future::plan("sequential" didn't help)

# needs to be set for large dataset analysis, SCTransform did not work with this set to 1E9
options(future.globals.maxSize = 5e9)

all_samples_merged_subset_norm<-SCTransform(all_samples_merged_subset,
    vars.to.regress = NULL, verbose = TRUE, conserve.memory = TRUE)

# ended up failing after 5 samples (I think) with this error: 
# Error: cannot allocate vector of size 72.1 Mb
# I think that means it ran out of RAM
# I'll try again tonight after removing the other objects from memory and closing all other programs


# STOPPED HERE 2026-06-03







#This is what we did the first time for normalization
all_samples_merged <- NormalizeData(all_samples_merged, normalization.method = "LogNormalize", scale.factor = 10000)

# save merged seurat object
write_rds(all_samples_merged, "data/rds_files/02-merged.rds")
```



```{r}
# THIS CHUNK CREATES A SKETCH AND DOES SOME PROCESSING

# create a "sketch" containing `ncells` cells per sample
# this takes a long time
sketch <- SketchData(
  object = all_of_them_merged,
  ncells = 1000,
  method = "LeverageScore",
  sketched.assay = "sketch",
  # see comment below explaining this next line 
  features = VariableFeatures(all_of_them_merged)
)

# we were getting this warning/error: "No variable features were found in data.1. Falling back to variable features from counts.1"
# In this link, it says if you have more than 5000 features total, it triggers that warning
# https://github.com/satijalab/seurat/issues/7171
# To remove the warning, add the line specifying which features are variable
# but then you get a new warning: LeverageScore failed on full matrix, retrying with same data (no zero-variance features found).

# save sketch
write_rds(sketch, "data/rds_files/03-sketch-raw.rds")

# switch to analyzing the full dataset (on-disk)
DefaultAssay(sketch) <- "RNA"
# switch to analyzing the sketched dataset (in-memory)
DefaultAssay(sketch) <- "sketch"

# do a bunch of processing on the sketch
sketch <- FindVariableFeatures(sketch)
sketch <- ScaleData(sketch)
sketch <- RunPCA(sketch)
sketch <- FindNeighbors(sketch, dims = 1:50)
sketch <- FindClusters(sketch, resolution = 2)
sketch <- RunUMAP(sketch, dims = 1:50, return.model = T)

# save processed sketch
write_rds(sketch, "data/rds_files/04-sketch-final.rds")
sketch<-read_rds("data/rds_files/04-sketch-final.rds")

DimPlot(sketch, label = T, label.size = 3, reduction = "umap", group.by = "Sample") + NoLegend()


DimPlot(sketch, label = T, label.size = 3, reduction = "pca", group.by = "Sample") + NoLegend()


#Now you do integration
```

```{r}
sessionInfo()
```