---
title: "progress notes"
author: "CNL"
date: "2026-07-08"
output: html_document
---

This is in REVERSE CHRONOLOGICAL order because Claire likes it that way

#2026-10-02
We have some results to look at. 

RLC on hyak did find all markers for cell type IE How is this cluster different from all other clusters (and this night from all other nights). 
She tried some ways to speed up the analysis using parallelization  and putting thresholds on the logFC but it didn't seem like either strategy was much faster. On the sketch it only takes like 10min so we don't know why this isn't better. She ended up doing the cell type DE on a subset of 500 cells which is recommended in a seurat tutorial. 

Sean did on his computer:

Differential gene expression results (follicular vs luteal) for all populations except CD16 NK cells, CD14 monocytes, and CD4 T cells. These cell populations were too large for the code to finish in a reasonable amount of time.

He did the cell type DE tests ONLY on the sketch


From Sean yesterday on slack

For tomorrow my computer has .csv files containing the results of the analyses we set up at our last meeting. Specifically:

FindAllMarkers output for each of our cell annotations (i.e. which markers are associated with each cell type). We planned to use these to create a dot plot showing the defining characteristics of each cell type.
I made some changes to the code to run FindAllMarkers on the sketch cells instead of on all the cells. It was too slow on all the cells. I pushed those changes just a few minutes ago.  

Differential gene expression results (follicular vs luteal) for all populations except CD16 NK cells, CD14 monocytes, and CD4 T cells. These cell populations were too large for the code to finish in a reasonable amount of time. I'm not confident that these results are actually right/testing what we want to be testing. 


We're comparing the UMAP resulting from RLC's run vs Sean's runon the sketch and then projection to the full data set. The shapes are different because we didn't set.seed but the content seems more or less similar. 

RLC was concerned that we annotated things as CD4 and CD8 differently than azimuth. She made umaps of just azimuth defined CD4 and CD8 expression and they seemed to cover different areas than what we designated as those groups in the our-annotation heat map.  She was able to run the full data set with azimuth. 

Discussed increasing the resolution of our clustering on the sketch which would give us more clusters. This might make our annotations closer to azimuth which looks at each cells and assigns labels rather than clustering. 

When we made our_annotations, we named a cluster based on the cell type that azimuth designated to at least 60% of the cells. When changed that to 90% but then we just had most of our cells designated as "uncertain". 

What is the goal of trying to match our annotations to azimuth? If the goal is to fact check azimuth maybe there are other ways to do that, like compare gene expression across the assigned groups. 


Ran into the duplicate values problem again when trying to make a dot plot. This happens when you have NA as the value for whatever label you're trying to use. Remove rows with NA's from the data set to proceed

no_na<-subset(annotated, subset  = !is.na(azimuth_medium))

Then plot the no_na object.

RLC suggests clustering with a lower resolution to make it easier to manually assign cell types to clusters. 

Possible plan: do a low resolution clustering and first assign major cell types then run the clustering again on each "major" group. 


#2026-09-24
Decided to manually map the cluster info that we got from azimuth onto the full data set. Since some clusters have multiple cell type designations, we chose the designation that was assigned to at least 70% of cells in the cluster. If it was less than that, we just p=labeled it as "not confident". This required turning rownames (the cell identifier) into a column, joining, then turning it back into rownames to fit the required formatting of the object. The rownames are cell identifiers. But then we couldn't make a DotPlot with the newly annotated full data set. It claimed that we had duplicate row names. Did various incantations, got it to work.

We started doing FindAllMarkers with our annotations so that we could do make another DotPlot with what the computer finds, not just our sanity check phenotyping markers (yes, CD4 is expressed by the cluster we called CD4 cells). That would require us to joinLayers and that would take a long time so we moved on to our pseudobulk analysis. 
We tried to use MAST as the test type (default is Wilcoxon) but it wasn't an option. 

you use AggregateExpression to pseudobulk the cells together and then you can do differential expression analysis between the two phases (F and L). So we're pretending we did bulk RNAseq for F and L samples and are looking for DEGs.

FYI FindAllMarkers is different from FindMarkers. In the latter you specify which things you want to compare and in the former it automatically compares everything against everything. 

We stopped after looking at  the DE genes for the pseudobulked data in a few cell types. We only did the test on a subset of 100 cells though since it would take forever. Sean will rerun over night and also run the JoinLayers for the we could do make another DotPlot with what the computer finds using FindAllMArkers, not just our sanity check phenotyping markers

# 2026-09-03
We're picking up at azimuth. RLC suggested using the FindAllMarkers seurat functions to look for DEGs between the clusters. You can ask for "positive" markers, ie what is in that cluster that isn't expressed in others or "negative" what is NOT in a particular cluster compared to others. You need to run JoinLayers before FindAllMarkers. I think there is one layer per sample and we need to put them all together. 
Following this V5 tutorial https://satijalab.org/seurat/articles/pbmc3k_tutorial

We're doing FindAllMarkers on the sketch, not the full data set because it was taking too long. We already projected the sketch onto the full set but then decided to go back to the sketch. 

We made a DotPlot() of expression of some of our favorite phenotyping genes and were able to identify major cell groups. There are some clusters that don't seem to be expressing much of anyhting. RLC said that these could be cells that are dead or expressing few genes or a lot of mt gene and are therefore clustering together for that reason, not because they are actually the same cell type. You can make a plot with those clsuters of your QC variables like nCount and mt% to see if they are indeed bad quality cells and should be removed. 
We did umap plots with nCount, nFeature and percent.mt and did not see any obvious "junk" clusters, ie, higher %mt and low gene counts. remember that we have already done an initial filter on these parameters. 

TODO
Double detection, we appear to have  clusters that are multiplets, ie expressing markers that we would not expect to coocur. 


We subsetted our sketch data to just monocytes (cells that were labeled by azimuth as monocytes).
We want to look at DEGs within monocytes that are different between phases. First we need to pseudobulk the data--pretend it is bulk RNAseq not single cells, because we're interested in differences between phases for all monocytes, not on a per cell basis. This causes our data to be collapsed into 24 samples (2 per donor) instead of like a million if we had kept it as non bulk. 

It looks like there are no sig diffs between phases but we're not sure how to account for pairing in this test. Internet tells me that if you switch to a different type of test you can include some type of pairing.

Friction: only our sketch has the azimuth data, the full data set only has clusters. 

Got stuck at trying to project the sketch with the azimuth data back onto the full data set to subsequently do DE tests on all the cells. (?) The problem maybe wasn't with azimuth, I don't know what's going on.


# 2026-07-08 group meeting
Previous Leon says:
In our group script, we have only used NormalizeData, not scTransform, because we don’t have enough computing power. RLC used Hyak to run scTransform though. 
Then we made a sketch with just 1k cells, scaled the data and did FindVariableFeatures and made umaps.
We did an integration on the sketch and did some umaps to compare integrated and non-integrated
Last time we tested out using Azimuth to annotate cells.

Do we use scTransform or NormalizeData?

QP says that Eva was never able to get scTransform to work with mast (Gottardo software). We thought scTransform would be better since it is the newer package but it might not be practical

It appears mast isn't supposed to be run on normalized data? 

Here's the MAST paper https://pubmed.ncbi.nlm.nih.gov/26653891/

We can ask Eva what has or hasn't worked.

Getting BPcells to work to reduce the size of the normalized object is probably not worth it if we aren't going to use scTransform. We previously used BP cells to put the original Seurat object on disk to save memory.

https://github.com/RGLab/MAST still works


Integrate or not? We decided no.

Pro: ?? Might 
In the vignette they need do it because they compare control vs stimulated pbmc, which are very different. IE it leads to the SAME cells be slightly different because of the stim. The tell-tale sign in the umap when they color by stim or not and that shows that they are clearly separated based on that. Then when they color by cell type there are clearly multiple populations for each subtype.
Con: we might lose some important variation

Next step: project the analysis done on the sketch for the full data set

First, we're changing the number of PCs to 30 based on the elbow plot that Quinn posted in slack. 